### ISSUE TITLE
关于青龙2.11.3版本

### ISSUE THREAD

**Issue by yunzimo** [KD-happy/KDCheckin#10]
请问我该如何适配青龙2.11版本，由于2.12版本目录的更改，我无法直接使用您的脚本。
直接使用出现的问题是KDconfig module找不到
`   from KDconfig import getYmlConfig, send
ModuleNotFoundError: No module named 'KDconfig'`
我尝试将KDconfig.py从KDsrc中移到外面，这个错误应该是没有了但是还有其他的问题：
`from KDsrc.AiHao import AiHao
ModuleNotFoundError: No module named 'KDsrc.AiHao'`
我是一个新手，不是很明白青龙脚本中python是如何处理这些依赖的。我该如何处理这些问题呢，我想过是否需要把所有文件都放在一起，然后修改more.py，但这是否违背了您分目录的初衷？请帮帮我

**Comment by KD-happy** [comment]
你可以看一下我提交的历史，有一个是“青龙最新版本适配”，估计你要修改相关的代码。

**Comment by KD-happy** [comment]
这两张是我设备本地里面的路径，估计你老版本是 `/ql/scripts`，你可以在本地修改相关文件的位置
![image](https://user-images.githubusercontent.com/67636118/227419823-0060545b-980b-4769-8889-73b57991885e.png)
![image](https://user-images.githubusercontent.com/67636118/227420042-82ba722b-bf83-4c5d-887f-14b43eee3e91.png)

这是你要修改的代码，因为qinglong执行的还是容器里面的地址（需要删掉`/data`）
修改的文件地址是`/ql/data/scripts/KD-happy_KDCheckin/KDconfig.py`（老版本 `/ql/scripts/KD-happy_KDCheckin/KDconfig.py`）
![image](https://user-images.githubusercontent.com/67636118/227420145-1db9e7d8-2e4d-42c1-bad7-50b9bbbc01d2.png)

这是青龙里面的真实地址，老版本是没有 `ql/data` 的，，这就为你可以理解相关的位置
![image](https://user-images.githubusercontent.com/67636118/227421115-6fde3640-b5bc-425b-a1f8-269461d8fb92.png)

**Comment by yunzimo** [comment]
> 这两张是我设备本地里面的路径，估计你老版本是 `/ql/scripts`，你可以在本地修改相关文件的位置 ![image](https://user-images.githubusercontent.com/67636118/227419823-0060545b-980b-4769-8889-73b57991885e.png) ![image](https://user-images.githubusercontent.com/67636118/227420042-82ba722b-bf83-4c5d-887f-14b43eee3e91.png)
> 
> 这是你要修改的代码，因为qinglong执行的还是容器里面的地址（需要删掉`/data`） 修改的文件地址是`/ql/data/scripts/KD-happy_KDCheckin/KDconfig.py`（老版本 `/ql/scripts/KD-happy_KDCheckin/KDconfig.py`） ![image](https://user-images.githubusercontent.com/67636118/227420145-1db9e7d8-2e4d-42c1-bad7-50b9bbbc01d2.png)
> 
> 这是青龙里面的真实地址，老版本是没有 `ql/data` 的，，这就为你可以理解相关的位置 ![image](https://user-images.githubusercontent.com/67636118/227421115-6fde3640-b5bc-425b-a1f8-269461d8fb92.png)

我大概明白你的意思了，我尝试了这样的拉库命令，并修改了KDconfig.py文件，他可以正确识别了：
`ql repo https://github.com/KD-happy/KDCheckin.git "AiHao|DuoKan|QianDao|Weather|News" "" "KD"
\cp -f /ql/repo/KD-happy_KDCheckin/*.py /ql/scripts/KD-happy_KDCheckin/KDsrc
\cp -f /ql/repo/yunzimo_KDCheckin/KDsrc/Cookie.yml /ql/config/Cookie.yml`
拉库命令中的参数`"KD"`是把KDsrc下的所有脚本都当做依赖的意思么

**Comment by yunzimo** [comment]
我大概明白你的意思了，我尝试了这样的拉库命令，并修改了**KDconfig.py**文件，他可以正确识别了：
`ql repo https://github.com/KD-happy/KDCheckin.git "AiHao|DuoKan|QianDao|Weather|News" "" "KD" \cp -f /ql/repo/KD-happy_KDCheckin/*.py /ql/scripts/KD-happy_KDCheckin/KDsrc \cp -f /ql/repo/yunzimo_KDCheckin/KDsrc/Cookie.yml /ql/config/Cookie.yml`
拉库命令中的参数`"KD"`是把**KDsrc**下的所有脚本都当做依赖的意思么

**Comment by KD-happy** [comment]
是的，你用的拉库命令，小心把自己的配置的cookie给覆盖了（第二个 cp -f）。

**Comment by yunzimo** [comment]
好的，明白
