### ISSUE TITLE
oppo商城可以上架了

### ISSUE THREAD

**Issue by geelinsir** [KD-happy/KDCheckin#11]
官方已取消强制验证码

**Comment by KD-happy** [comment]
现在还有人稀罕oppo积分？？感觉都兑换不了啥东西了，而且签到给的少的要死，没以前好了。

说真的，就是好多人来薅oppo的羊毛，导致现在签到积分少的。算了不想搞咯，你如果想玩，你可以看一下提交历史，或者看原作者吧。

（题外话，1到3月我到期的积分都有20000多，这还是我之前天天签到的。自从没有签到满7天，每天送10积分的签到规则，我都不想签了）
