### ISSUE TITLE
百度贴吧返回值异常

### ISSUE THREAD

**Issue by KingFuRong** [KD-happy/KDCheckin#12]
![Screenshot_2023-04-10-12-04-22-343_com microsoft emmx](https://user-images.githubusercontent.com/119987402/230823635-f57d60c3-a83e-4e44-b6a5-7e58ff36ffbe.png)
![Screenshot_2023-04-10-12-06-04-304_com baidu tieba](https://user-images.githubusercontent.com/119987402/230823701-d8e5465c-fcac-42dd-9cb9-054140f8efec.png)

**Comment by KD-happy** [comment]
> ![Screenshot_2023-04-10-12-04-22-343_com microsoft emmx](https://user-images.githubusercontent.com/119987402/230823635-f57d60c3-a83e-4e44-b6a5-7e58ff36ffbe.png)
> ![Screenshot_2023-04-10-12-06-04-304_com baidu tieba](https://user-images.githubusercontent.com/119987402/230823701-d8e5465c-fcac-42dd-9cb9-054140f8efec.png)
> 

现在已经好了，就改了一个https，，，

温馨提醒：我不知道百度贴吧怎么说，我的百度文库的账号以前刷签到，被封了，直接不给签到。怎么说呢最好别搞百度的签到。

**Comment by KingFuRong** [comment]
好的，万分感谢

**Comment by KingFuRong** [comment]
好像还是查不到贴吧数量QWQ

**Comment by KD-happy** [comment]
> 好像还是查不到贴吧数量QWQ

估计你的cookie配置问题，stoken要是贴吧的，不是百度的，你试试

**Comment by KingFuRong** [comment]
![Screenshot_2023-04-10-13-42-01-577_bin mt plus-edit](https://user-images.githubusercontent.com/119987402/230834450-2cfac16a-bc33-45ae-b5e9-c93eeb0b2f84.jpg)
百度贴吧APP里面抓的

**Comment by KD-happy** [comment]
> ![Screenshot_2023-04-10-13-42-01-577_bin mt plus-edit](https://user-images.githubusercontent.com/119987402/230834450-2cfac16a-bc33-45ae-b5e9-c93eeb0b2f84.jpg)
> 百度贴吧APP里面抓的

额，xxxx=xxx; xxxx=xxxx     中间加个空格？？

**Comment by KingFuRong** [comment]
不好意思，忘了要加空格了，sry
