### ISSUE TITLE
能否支持传参运行

### ISSUE THREAD

**Issue by geelinsir** [KD-happy/KDCheckin#13]
即不依靠Cookie.yml，直接获取set cookie={}的参数来运行，目前看代码写的是只要没有Cookie.yml就不运行

**Comment by KD-happy** [comment]
暂不支持，估计以后也不会支持，毕竟模板放在这了，不想搞额外的东西了。

**Comment by geelinsir** [comment]
如果我PR的话可以接受吗

**Comment by geelinsir** [comment]
另外W2PJ脚本目前正常吗，我这边报错p1 = re.findall('\|\/(.*=)\|', res.text)[0]
IndexError: list index out of range
