### ISSUE TITLE
QianDao.py运行报错

### ISSUE THREAD

**Issue by sunny7010** [KD-happy/KDCheckin#19]
开始运行...

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/workspace/KDCheckin/QianDao.py", line 9, in <module>
    from KDsrc.more import map
  File "/workspace/KDCheckin/KDsrc/more.py", line 4, in <module>
    from KDsrc.AcFun import AcFun
ModuleNotFoundError: No module named 'KDsrc.AcFun'

运行结束。

**Comment by KD-happy** [comment]
如果想使用qiandao.py，需要将所有的.py文件复制到KSsrc文件夹中，最基本的python知识。对应拉取本站的第二条命令。
