### ISSUE TITLE
BLBL分享失败

### ISSUE THREAD

**Issue by sunny7010** [KD-happy/KDCheckin#20]
开始运行...

WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
【哔哩哔哩 日志】
好名字7010 开始签到...
{'code': 1011040, 'message': '今日已签到过,无法重复签到', 'ttl': 1, 'data': None}
直播签到: 重复签到
{'code': 'invalid_argument', 'msg': 'clockin clockin is duplicate', 'meta': {'argument': 'clockin'}}
漫画签到: 重复签到
{'code': 0, 'message': '0', 'ttl': 1, 'data': {'login': True, 'watch': True, 'coins': 0, 'share': False, 'email': True, 'tel': True, 'safe_question': True, 'identify_card': True}}
今日经验: 10
观看视频: 今日已完成
{"code":-403,"message":"账号异常,操作失败","ttl":1}
分享任务: 账号异常,操作失败
307120340: 投币成功
770469134: 投币成功
479558038: 投币成功
投币任务: 5/5
{'code': 0, 'message': '0', 'ttl': 1, 'data': {'login': True, 'watch': True, 'coins': 50, 'share': False, 'email': True, 'tel': True, 'safe_question': True, 'identify_card': True}}
今日经验: 60
{"code":403,"data":{"coin":0,"gold":0,"silver":0,"tid":""},"message":"银瓜子余额不足"}
当前硬币和银币数: 132/686
免费礼物: 赠送失败

【哔哩哔哩】
账号信息: 好名字7010
直播签到: 重复签到
漫画签到: 重复签到
观看视频: 今日已完成
分享任务: 账号异常,操作失败
投币任务: 5/5
今日经验: 60
银瓜子兑硬币: 银瓜子余额不足
当前硬币和银币数: 132/686
主播ID错误
主播ID错误
免费礼物: 赠送失败

gocq 推送未配置, 推送失败
pushplus 推送完成
push+ 推送未配置, 推送失败
ding 推送未配置, 推送失败
ding 推送失败, 查看一下配置文件
qywx 推送未配置, 推送失败

运行结束。

**Comment by KD-happy** [comment]
视频分享失败，我是知道的，没办法修复，，，，
