### ISSUE TITLE
[Bug or Not]本地post失败，返回<Response [404]>

### ISSUE THREAD

**Issue by MengFanwei0317** [KD-happy/KDCheckin#24]
脚本post https://www.acfun.cn/rest/pc-direct/user/signIn 失败，但是直接点击会得到准确的返回值{
    "result": 122,
    "msg": "今日已签到",
    "error_msg": "今日已签到",
    "host-name": "hb2-acfun-kce-node158.aliyun"
}
把代码在本地运行了以下，发现返回的是<Response [401]>
我查看了AcFun 的API调用，在每日签到里面并没有要求有请求参数，请问下大家是怎么运行的
另外，我的cookie填写了auth_key和acPasstoken

**Comment by GUETdelaji** [comment]
破案了，在AcFun.py Line172 for item in self.cookie.split("; ") 这行代码里面;后面跟了一个空格
删去这个空格或者在Cookie.yml里面在auth_key和acPasstoken中间的;后面手动添加一个空格即可运行
