### ISSUE TITLE
请教？

### ISSUE THREAD

**Issue by GD2021** [KD-happy/KDCheckin#3]
![image](https://user-images.githubusercontent.com/81171294/171872411-f8c02526-c93d-43f3-8a51-a8aaf794e46f.png)
请问这是怎么回事？

**Comment by KD-happy** [comment]
这不是运行qinglong里面的命令

想在qinglong执行就执行下面的
```shell
cp /ql/data/repo/KD-happy_KDCheckin/Cookie.yml /ql/data/config/Cookie.yml
```

**Comment by GD2021** [comment]
谢谢！！！
