### ISSUE TITLE
小白求解

### ISSUE THREAD

**Issue by yqc2003** [KD-happy/KDCheckin#4]
作者大大，腾讯云函数的一键脚本是需要cd src后在执行吗，我是要修改KDCheckin文件夹下的Cookie.yml文件还是修改src文件夹下的Cookie.yml文件，烦请作者大大解答

**Comment by KD-happy** [comment]
腾讯函数早就不用了。你复制的`curl https://cdn.jsdelivr.net/gh/KD-happy/KDCheckin@main/other/go.sh|bash`，在当前函数的根目录下执行。配置文件是配置src下面的Cookie.yml
