### ISSUE TITLE
AttributeError: module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by qgdyyg** [KD-happy/KDCheckin#8]
签到一次后出现这个情况
## 开始执行... 2022-07-09 00:11:50

Traceback (most recent call last):
  File "/ql/data/scripts/KD-happy_KDCheckin/QianDao.py", line 13, in <module>
    config = getYmlConfig()
  File "/ql/data/scripts/KD-happy_KDCheckin/KDconfig.py", line 21, in getYmlConfig
    config = yaml.load(file_data, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

## 执行结束... 2022-07-09 00:11:50 耗时 0 秒
我去找方法，用这个 pip install --ignore-installed PyYAML 解决的
不知道什么情况，先反映给作者再说

**Comment by KD-happy** [comment]
我也不知道，没出现过这种情况，有可能你没有按照相关库吧

下面是要安装的库，执行一下就行了

```shell
pip install requests pyyaml bs4
```

或者在青龙的依赖添加如下

![image](https://user-images.githubusercontent.com/67636118/178075409-738f977a-2cc1-4cd4-a1c7-e3f20a8c5e17.png)
